v2.0.0

diff --git a/.github/workflows/demo.yaml b/.github/workflows/demo.yaml
--- a/.github/workflows/demo.yaml
+++ b/.github/workflows/demo.yaml
@@ -9,6 +9,9 @@ on:
         default: 1
         required: true
 
+env:
+  ACTION_STATUS: failure
+
 jobs:
   try:
     runs-on: ubuntu-latest
@@ -16,28 +19,42 @@ jobs:
     - name: "checkout"
       uses: actions/checkout@v4
 
-    - name: "check script"
-      shell: bash
+    - name: "main execution"
+      id: "main-execution"
       run: |
-        #! /bin/bash
-        num_retry=${{ inputs.num_retry }}
-        max_try=$((num_retry + 1))        
+        exit 1
 
-        echo "===============> $max_try"
+    - name: "retries"
+      id: "retries"
+      if: ${{ failure() }}
+      run: |
+        echo "HI :)"
 
-        set +e
 
-        n=0
-        while (( n < max_try )); do
-            echo "============================================================================="
-            echo "Running testcase"
-            echo "============================================================================="
-            echo "loop $n"
-            ./script.sh $n && break
-            ((n++))
-        done
+    # - name: "check script"
+    #   shell: bash
+    #   run: |
+    #     #! /bin/bash
+    #     num_retry=${{ inputs.num_retry }}
+    #     max_try=$((num_retry + 1))        
 
-        if (( n == max_try )); then
-            echo "Command failed after $max_try attempts"
-            exit 1
-        fi
+    #     echo "===============> $max_try"
+
+    #     set +e
+
+    #     n=0
+    #     while (( n < max_try )); do
+    #         echo "============================================================================="
+    #         echo "Running testcase"
+    #         echo "============================================================================="
+    #         echo "loop $n"
+    #         ./script.sh $n && break
+    #         ((n++))
+    #     done
+
+        # if (( n == max_try )); then
+        #     echo "Command failed after $max_try attempts"
+        #     exit 1
+        # fi
+
+# if main fails (X) => retry (conclusion must be based on the overall but main must be marked as failure)
