update

diff --git a/.github/workflows/retry.yaml b/.github/workflows/retry.yaml
--- a/.github/workflows/retry.yaml
+++ b/.github/workflows/retry.yaml
@@ -31,6 +31,7 @@ permissions:
 
 jobs:
   retry:
+    if: ${{ inputs['caller-result'] == 'failure' }}  
     runs-on: ubuntu-latest
     steps:
     - name: checkout
@@ -44,20 +45,20 @@ jobs:
     - name: retry
       run: python -u .github/retry.py  --token "${{ secrets.GITHUB_TOKEN }}" --retry "${{ inputs.retry }}" --workflow "${{ inputs.caller-name }}" --data "${{ inputs.caller-data }}"
 
-  on-failure:
-    needs: retry
-    if: ${{ inputs['caller-result'] == 'failure' }}  
-    runs-on: ubuntu-latest
-    steps:
-    - run: |
-        echo $'\u274C'
-        exit 1
+  # on-failure:
+  #   needs: retry
+  #   if: ${{ inputs['caller-result'] == 'failure' }}  
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - run: |
+  #       echo $'\u274C'
+  #       exit 1
 
-  on-success:
-    needs: retry
-    if: ${{ inputs['caller-result'] == 'success' }}  
-    runs-on: ubuntu-latest
-    steps:
-    - run: |
-        echo $'\u2705'
-        exit 0
+  # on-success:
+  #   needs: retry
+  #   if: ${{ inputs['caller-result'] == 'success' }}  
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - run: |
+  #       echo $'\u2705'
+  #       exit 0
